---
apiVersion: v1
kind: Template
labels:
  template: boot-spring-template
metadata:
  creationTimestamp: null
  annotations:
    tags: boot-spring
  name: boot-spring-template
objects:
-   apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      name: ${APP_NAME}
      namespace: ${PROJECT_NAME}
      labels:
        app: ${APP_NAME}
    spec:
      nodeSelector: null
      output:
        to:
          kind: ImageStreamTag
          name: '${APP_NAME}:latest'
      resources: {}
      successfulBuildsHistoryLimit: 5
      failedBuildsHistoryLimit: 5
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            namespace: openshift
            name: 'java:8'
      postCommit: {}
      source:
        type: Git
        git:
          uri: ${APP_GIT_URL}
      triggers:
        - type: ImageChange
          imageChange:
        - type: ConfigChange
      runPolicy: Serial

-   apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      name: ${APP_NAME}
      namespace: ${PROJECT_NAME}
      generation: 1
      labels:
        app: ${APP_NAME}
    spec:
      lookupPolicy:
        local: false
    
-   apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      name: ${APP_NAME}
      namespace: ${PROJECT_NAME}
      generation: 2
      labels:
        app: ${APP_NAME}
    spec:
      strategy:
        type: Rolling
        rollingParams:
          updatePeriodSeconds: 1
          intervalSeconds: 1
          timeoutSeconds: 600
          maxUnavailable: 25%
          maxSurge: 25%
        resources: {}
        activeDeadlineSeconds: 21600
      triggers:
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - ${APP_NAME}
            from:
              kind: ImageStreamTag
              namespace: ${PROJECT_NAME}
              name: '${APP_NAME}:latest'
        - type: ConfigChange
      replicas: ${{POD_COUNT}}
      revisionHistoryLimit: 10
      test: false
      selector:
        app: ${APP_NAME}
        deploymentconfig: ${APP_NAME}
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: ${APP_NAME}
            deploymentconfig: ${APP_NAME}
        spec:
          containers:
            - name: ${APP_NAME}
              image: >-
                image-registry.openshift-image-registry.svc:5000/${PROJECT_NAME}/boot-spring@sha256:5e1e27d2bde909cd6a164b27d0c6817088792d6d701e96ba847d2154d99b44be
              ports:
                - containerPort: 8080
                  protocol: TCP
                - containerPort: 8443
                  protocol: TCP
                - containerPort: 8778
                  protocol: TCP
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              imagePullPolicy: Always
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          schedulerName: default-scheduler
      
-   apiVersion: v1
    kind: Service
    metadata:
      name: ${APP_NAME}
      namespace: ${PROJECT_NAME}
      labels:
        app: boot-spring
    spec:
      ports:
        - name: 8080-tcp
          protocol: TCP
          port: 8080
          targetPort: 8080
      selector:
        app: ${APP_NAME}
        deploymentconfig: ${APP_NAME}
      clusterIP: 172.30.100.17
      type: ClusterIP
      sessionAffinity: None

-   apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: ${APP_NAME}
      namespace: ${PROJECT_NAME}
      labels:
        app: ${APP_NAME}
      annotations:
        openshift.io/host.generated: 'true'
    spec:
      host: >-
        ${APP_NAME}-${PROJECT_NAME}.apps.ca-central-1.starter.openshift-online.com
      subdomain: ''
      to:
        kind: Service
        name: ${APP_NAME}
        weight: 100
      port:
        targetPort: 8080-tcp
      wildcardPolicy: None
parameters:
- description: PROJECT_NAME
  displayName: PROJECT_NAME
  name: PROJECT_NAME
  required: true
- description: APP_NAME
  displayName: APP_NAME
  name: APP_NAME
  required: true
- description: APP_GIT_URL
  displayName: APP_GIT_URL
  name: APP_GIT_URL
  required: true
- description: POD_COUNT
  displayName: POD_COUNT
  name: POD_COUNT
  required: true
